version: 0.2

env:
  variables:
    NODE_VERSION: "8.11.1"
    YARN_VERSION: "1.5.1"
    NODE_ENV: "development"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget "https://nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" -O "node-v$NODE_VERSION-linux-x64.tar.gz"
      - tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1
      - rm "node-v$NODE_VERSION-linux-x64.tar.gz"
      - ln -s /usr/local/bin/node /usr/local/bin/nodejs
      - npm install -g "yarn@$YARN_VERSION"
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
      - yarn install --non-interactive --frozen-lockfile
      - yarn run ci:prepare
  build:
    commands:
      - echo Entered the build phase...
      - yarn run ci
  post_build:
    commands:
      - echo Entered the post_build phase...
      - yarn run ci:cleanup
