adminSettingsTab:
  announcementHeader:
    en: Global announcement
    de: Globale Ankündigung
  consentHeader:
    en: Consent text
    de: Zustimmungstext
  homepageDocumentsHeader:
    en: Homepage documents pool
    de: Homepage-Dokumente-Becken ))
  helpPageHeader:
    en: Help page
    de: Hilfe-Seite
  termsPageHeader:
    en: Terms of usage page
    de: Nutzungsbedingungen-Seite
  footerLinksHeader:
    en: Footer links
    de: Footer-Links
  templateDocumentHeader:
    en: Template for new documents
    de: Vorlage für neue Dokumente
  licenseHeader:
    en: License
    de: Lizenz
  pluginsHelpTextsHeader:
    en: Help texts for plugins
    de: Hilfetexte für Plugins
