adminSettingsTab:
  announcementHeader:
    en: Global announcement
    de: Globale Ankündigung
  announcementInfo:
    en: This announcement is shown under the website header on all pages. Users can close it and it will only appear again when the text or type are changed.
    de: Diese Ankündigung wird auf allen Seiten unter dem Website-Header angezeigt. Benutzer können sie schließen, und sie wird erst wieder erscheinen, wenn sich der Text oder Typ geändert hat.
  consentHeader:
    en: Consent text
    de: Zustimmungstext
  homepageTagsHeader:
    en: Homepage recommended tags
    de: Empfohlene Tags auf der Homepage
  homepageTagsInfo:
    en: These tags appear as recommended searched on the homepage. When they are not set, the top 5 most used tags are recommended.
    de: Diese Tags erscheinen als empfohlene Suchbegriffe auf der Homepage. Wenn sie nicht gesetzt sind, werden die 5 am häufigsten verwendeten Tags empfohlen.
  homepageDocumentsHeader:
    en: Homepage documents pool
    de: Homepage-Dokumente-Fundus
  homepageDocumentsInfo:
    en: From this list, 3 documents are randomly selected and displayed on the homepage.
    de: Aus dieser Liste werden 3 zufällig ausgewählte Dokumente auf der Homepage angezeigt.
  homepagePresentationHeader:
    en: Homepage presentation
    de: Homepage-Präsentation
  homepageTrustLogosHeader:
    en: Homepage trust logos
    de: Homepage Vertrauens-Logos
  homepageTrustLogosInfo:
    en: The logos of the trusted institutions are displayed in an extra footer on the homepage. Please provide SVGs with transparent background and links to the home pages of each institution.
    de: The logos of the trusted institutions are displayed in an extra footer on the homepage. Please provide SVGs with transparent background and links to the home pages of each institution.
  helpPageHeader:
    en: Help page
    de: Hilfe-Seite
  termsPageHeader:
    en: Terms of usage page
    de: Nutzungsbedingungen-Seite
  footerLinksHeader:
    en: Footer links
    de: Footer-Links
  templateDocumentHeader:
    en: Template for new documents
    de: Vorlage für neue Dokumente
  licenseHeader:
    en: License
    de: Lizenz
  pluginsHelpTextsHeader:
    en: Help texts for plugins
    de: Hilfetexte für Plugins
