homepageInfoHeader:
  en: Homepage info
  de: Homepage-Info
helpPageHeader:
  en: Help page
  de: Hilfe-Seite
termsPageHeader:
  en: Terms of usage page
  de: Nutzungsbedingungen-Seite
footerLinksHeader:
  en: Footer links
  de: Footer-Links
consentHeader:
  en: Consent text
  de: Zustimmungstext
documentRegenerationButton:
  en: Regenerate documents
  de: Dokumente neu erstellen
documentValidationButton:
  en: Validate documents
  de: Dokumente validieren
cdnResourcesConsolidationButton:
  en: Consolidate CDN resources
  de: CDN-Ressourcen konsolidieren
cdnUploadDirectoryCreationButton:
  en: Create CDN upload directories
  de: CDN-Upload-Verzeichnisse erstellen
templateDocumentHeader:
  en: Template for new documents
  de: Vorlage für neue Dokumente
licenseHeader:
  en: License
  de: Lizenz
technicalMaintenanceTasksHeader:
  en: Technical maintenance tasks
  de: Technische Instandhaltungsaufgaben
lastExecution:
  en: Last execution
  de: Letzte Ausführung
pluginsHelpTextsHeader:
  en: Help texts for plugins
  de: Hilfetexte für Plugins
