homepageInfoHeader:
  en: Homepage info
  de: Homepage-Info
helpPageHeader:
  en: Help page
  de: Hilfe-Seite
termsPageHeader:
  en: Terms of usage page
  de: Nutzungsbedingungen-Seite
footerLinksHeader:
  en: Footer links
  de: Footer-Links
consentHeader:
  en: Consent text
  de: Zustimmungstext
defaultTagsHeader:
  en: Default tags
  de: Vordefinierte Tags
documentRegenerationHeader:
  en: Document regeneration
  de: Dokumentwiederherstellung
documentRegenerationButton:
  en: Regenerate documents
  de: Dokumente neu erstellen
cdnResourcesConsolidationHeader:
  en: CDN resources consolidation
  de: Konsolidierung der CDN-Ressourcen
cdnResourcesConsolidationButton:
  en: Consolidate CDN resources
  de: CDN-Ressourcen konsolidieren
cdnUploadDirectoryCreationHeader:
  en: CDN upload directory creation
  de: Erstellung der CDN-Upload-Verzeichnisse
cdnUploadDirectoryCreationButton:
  en: Create CDN upload directories
  de: CDN-Upload-Verzeichnisse erstellen
templateDocumentHeader:
  en: Template for new documents
  de: Vorlage für neue Dokumente
licenseHeader:
  en: License
  de: Lizenz
dataMigrationHeader:
  en: Data migration
  de: Datenmigration
lastExecution:
  en: Last execution
  de: Letzte Ausführung
pluginsHelpTextsHeader:
  en: Plugins help texts
  de: Plugins-Hilfetexte
