announcementHeader:
  en: Announcement
  de: Mitteilung
announcementPreview:
  en: Preview
  de: Vorschau
homepageInfoHeader:
  en: Homepage info
  de: Homepage-Info
helpPageHeader:
  en: Help page
  de: Hilfe-Seite
termsPageHeader:
  en: Terms of usage page
  de: Nutzungsbedingungen-Seite
footerLinksHeader:
  en: Footer links
  de: Footer-Links
defaultTagsHeader:
  en: Default tags
  de: Vordefinierte Tags
createDocumentRegenerationBatchHeader:
  en: Document recreation
  de: Dokumentwiederherstellung
createDocumentRegenerationBatchButton:
  en: Regenerate documents
  de: Dokumente neu erstellen
templateDocumentHeader:
  en: Template for new documents
  de: Vorlage für neue Dokumente
