announcementHeader:
  en: Announcement
  de: Mitteilung
announcementPreview:
  en: Preview
  de: Vorschau
helpPageHeader:
  en: Help page
  de: Hilfe-Seite
termsPageHeader:
  en: Terms of usage page
  de: Nutzungsbedingungen-Seite
footerLinksHeader:
  en: Footer links
  de: Footer-Links
defaultTagsHeader:
  en: Default tags
  de: Vordefinierte Tags
createRegenerateDocumentsBatchHeader:
  en: Trigger document recreation
  de: Dokumentwiederherstellung auslösen
createRegenerateDocumentsBatch:
  en: Regenerate Documents
  de: Dokumente neu erstellen
