homeLanguagesHeader:
  en: Landing page languages
  de: Sprachen auf der Startseite
homeLanguagesSubHeader:
  en: The top most entry will be used as default
  de: Der oberste Eintrag wird als Standard benutzt
helpPageHeader:
  en: Help page
  de: Hilfe-Seite
termsPageHeader:
  en: Terms of usage page
  de: Nutzungsbedingungen-Seite
footerLinksHeader:
  en: Footer links
  de: Footer-Links
defaultTagsHeader:
  en: Default tags
  de: Vordefinierte Tags
