rank:
  en: Rank
  de: Rang
language:
  en: Language
  de: Sprache
documentKey:
  en: Document key
  de: Dokument-Schlüssel
searchFieldButton:
  en: Search field button
  de: Suchfeld-Button
searchFieldPlaceholder:
  en: Search field placeholder
  de: Suchfeld-Platzhalter
