name: Build Commit
on: [push]
jobs:
  build-elmu:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
      ELMU_ENV: test
    services:
      minio:
        image: bitnami/minio:2020.12.18
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "UVDXF41PYEAX0PXD8826"
          MINIO_SECRET_KEY: "SXtajmM3uahrQ1ALECh3Z3iKT76s2s5GBJlbQMZx"
          MINIO_BROWSER: "on"
          MINIO_DOMAIN: "localhost"
      mongo:
        image: bitnami/mongodb:4.2.17-debian-10-r23
        ports:
          - 27017:27017
        env:
          MONGODB_ROOT_USER: root
          MONGODB_ROOT_PASSWORD: rootpw
          MONGODB_REPLICA_SET_KEY: elmurs
          MONGODB_REPLICA_SET_NAME: elmurs
          MONGODB_REPLICA_SET_MODE: primary
      maildev:
        image: maildev/maildev:1.1.0
        ports:
          - 8000:8000
    steps:
      - name: Change user
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.10.0"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Prepare build
        run: ./node_modules/.bin/gulp ciPrepare
      - name: Build
        run: ./node_modules/.bin/gulp ci
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
      - name: Create release info
        run: |
          echo "${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.$GITHUB_RUN_NUMBER" > ./dist/release.txt
      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy-release:
    runs-on: ubuntu-20.04
    needs: [build-elmu]
    if: github.ref == 'refs/heads/main'
    env:
      DOCKER_IMAGE: elmu/elmu-web
      OCTO_PROJECT_NAME: elmu-web
      OCTO_ENVIRONMENT_NAME: Staging
      OCTO_SERVER: https://elmu.octopus.app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Set RELEASE_NUMBER
        run: echo "RELEASE_NUMBER="$(cat ./dist/release.txt | tr -d '\n')"" >> $GITHUB_ENV
      - name: Create release notes
        run: echo "RELEASE_NOTES=$(echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_NUMBER }}
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
        with:
          version: latest
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v1.1.1
        with:
          api_key: ${{ secrets.OCTO_API_KEY }}
          project: ${{ env.OCTO_PROJECT_NAME }}
          server: ${{ env.OCTO_SERVER }}
          release_notes: ${{ env.RELEASE_NOTES }}
          release_number: ${{ env.RELEASE_NUMBER }}
          deploy_to: ${{ env.OCTO_ENVIRONMENT_NAME }}
