name: CI
on: [push]
jobs:
  verify:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
      EDUCANDU_ENV: test
    services:
      minio:
        image: bitnami/minio:2020.12.18
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "UVDXF41PYEAX0PXD8826"
          MINIO_SECRET_KEY: "SXtajmM3uahrQ1ALECh3Z3iKT76s2s5GBJlbQMZx"
          MINIO_BROWSER: "on"
          MINIO_DOMAIN: "localhost"
      mongo:
        image: bitnami/mongodb:4.2.17-debian-10-r23
        ports:
          - 27017:27017
        env:
          MONGODB_ROOT_USER: root
          MONGODB_ROOT_PASSWORD: rootpw
          MONGODB_REPLICA_SET_KEY: educandurs
          MONGODB_REPLICA_SET_NAME: educandurs
          MONGODB_REPLICA_SET_MODE: primary
      maildev:
        image: maildev/maildev:1.1.0
        ports:
          - 8000:8000
    steps:
      - name: Change user
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Lint
        run: ./node_modules/.bin/gulp lint
      - name: Test
        run: ./node_modules/.bin/gulp test
      - name: Codecov
        uses: codecov/codecov-action@v2
      - name: Authenticate for changelog
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
  publish-prerelease:
    runs-on: ubuntu-20.04
    needs: [verify]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix')
    env:
      NODE_ENV: development
      CHANGELOG_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Build library
        run: ./node_modules/.bin/gulp build
      - name: Install github changelog generator
        run: sudo gem install github_changelog_generator
      - name: Build release notes
        run:  ./node_modules/.bin/gulp generateChangelog
      - name: Write github token to file
        run: |
          echo "$CHANGELOG_GITHUB_TOKEN" > gitToken.txt
      - name: Authenticate for changelog
        run:  echo "$CHANGELOG_GITHUB_TOKEN" | gh auth login --with-token
      - name: Publish changelog
        run: gh release create "0.0.0-pre.$GITHUB_SHA" --notes-file CHANGELOG.md --title "0.0.0-pre.$GITHUB_SHA"
      - name: Authenticate with npm
        run: npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
      - name: npm version
        run: npm version --allow-same-version --git-tag-version=false "0.0.0-pre.$GITHUB_SHA"
      - name: npm publish
        run: npm publish
  publish-tag:
    runs-on: ubuntu-20.04
    needs: [verify]
    if: startsWith(github.ref, 'refs/tags/')
    env:
      NODE_ENV: development
      CHANGELOG_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.11.0"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Build library
        run: ./node_modules/.bin/gulp build
      - name: Install github changelog generator
        run: sudo gem install github_changelog_generator
      - name: Build release notes
        run:  ./node_modules/.bin/gulp generateChangelog
      - name: Authenticate for changelog
        run:  echo "$CHANGELOG_GITHUB_TOKEN" | gh auth login --with-token
      - name: Publish changelog
        run: gh release create ${{ steps.tag.outputs.tag }} --notes-file CHANGELOG.md --title ${{ steps.tag.outputs.tag }}
      - name: Authenticate with npm
        run: npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
      - name: npm version
        run: npm version --allow-same-version --git-tag-version=false ${{ steps.tag.outputs.tag }}
      - name: npm publish
        run: npm publish
