name: CI
on: [push]
jobs:
  build-elmu:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
      ELMU_ENV: test
    services:
      minio:
        image: bitnami/minio:2020.12.18
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "UVDXF41PYEAX0PXD8826"
          MINIO_SECRET_KEY: "SXtajmM3uahrQ1ALECh3Z3iKT76s2s5GBJlbQMZx"
          MINIO_BROWSER: "on"
          MINIO_DOMAIN: "localhost"
      mongo:
        image: bitnami/mongodb:4.2.17-debian-10-r23
        ports:
          - 27017:27017
        env:
          MONGODB_ROOT_USER: root
          MONGODB_ROOT_PASSWORD: rootpw
          MONGODB_REPLICA_SET_KEY: elmurs
          MONGODB_REPLICA_SET_NAME: elmurs
          MONGODB_REPLICA_SET_MODE: primary
      maildev:
        image: maildev/maildev:1.1.0
        ports:
          - 8000:8000
    steps:
      - name: Change user
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.10.0"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Prepare build
        run: ./node_modules/.bin/gulp ciPrepare
      - name: Build
        run: ./node_modules/.bin/gulp ci
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
      - name: Create release info
        run: |
          echo "${{ steps.current-time.outputs.year }}.${{ steps.current-time.outputs.month }}.${{ steps.current-time.outputs.day }}.$GITHUB_RUN_NUMBER" > ./dist/release.txt
      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
