name: Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: development
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      JIRA_USER: ${{secrets.JIRA_USER}}
      JIRA_API_KEY: ${{secrets.JIRA_API_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: "yarn"
      - name: Install node modules
        run: yarn install --non-interactive --check-files --frozen-lockfile
      - name: Get tag from build environment
        uses: dawidd6/action-get-tag@v1
        id: tag
      - name: Verify tag format
        run: ./node_modules/.bin/gulp verifyTag --tag ${{ steps.tag.outputs.tag }}
      - name: Set package version
        run: npm version --allow-same-version --git-tag-version=false ${{ steps.tag.outputs.tag }}
      - name: Build library
        run: ./node_modules/.bin/gulp build
      - name: Authenticate with npm
        run: npm set //registry.npmjs.org/:_authToken $NPM_AUTH_TOKEN
      - name: Publish to npm
        run: npm publish
      - name: Create Github release
        run:  ./node_modules/.bin/gulp release --tag ${{ steps.tag.outputs.tag }} --jira-user "$JIRA_USER" --jira-api-key "$JIRA_API_KEY"
